ALTER TABLE tag_registry ADD COLUMN IF NOT EXISTS unit VARCHAR(40) NULL;
ALTER TABLE tag_registry ADD COLUMN IF NOT EXISTS format VARCHAR(40) NULL;
ALTER TABLE tag_registry ADD COLUMN IF NOT EXISTS eng_min DOUBLE PRECISION NULL;
ALTER TABLE tag_registry ADD COLUMN IF NOT EXISTS eng_max DOUBLE PRECISION NULL;
